Draft: feat: use a custom haumea loader
divnix/hive pull request #33
Opened 2024-03-15 12:43 UTC by korrat

This patch replaces the scoped loader used in `load` with a custom version that can resolve module arguments as well.

2024-03-15 12:50 UTC, korrat commented
Once #32 is merged, we can rebase this branch on top of main.

One problem of this patch is that the scoped functionality does not match the function version exactly, due to the way the imports work. I don't believe that will be fixable. Therefore, I left the `pkgs` argument on the module definition in `load`. Consumers can then rely on `cell`, `config`, `inputs`, `lib`, `modulesPath`, `options`, and `pkgs` being in scope, while for all other arguments, they would have to declare a function. Is that a good compromise?

2024-03-15 17:00 UTC, korrat commented
The first commit (apart from the one included in #32) works with https://github.com/Lord-Valen/configuration.nix.

The second commit replaces the custom loader implementation with `applyModuleArgsIfFunction`, mostly. However, that causes some failures, since now `config`, `lib`, and `options` are **always** passed. Could be worth it for the reduced maintenance, but would cause some more churn for users. Also, it yields a warning about external calls to the function being deprecated.

2025-02-13 19:02 UTC, korrat commented
Pinging @blaggacao: Was there something to fix/change about this PR? Or is it no longer relevant?

2025-02-13 21:45 UTC, blaggacao commented
I've just looked at this (again ?). Could you introduce me to this PR from the end backwards, just to give me a little head start with the review?

- Why do we want to "can resolve module arguments as well." ? Might be obvious in-context, I'm just not creative as out of context as I currently am.

- Is the refactoring of `defaultWith` a guaranteed to be non-function-altering refactoring or does it alter function? If it does, please also introduce me from the end to the functional change in detail.

Happy to onboard myself and review, then.

2025-02-14 17:12 UTC, korrat commented
> I've just looked at this (again ?). Could you introduce me to this PR from the end backwards, just to give me a little head start with the review?

Sure. I could've described the PR way better in general.

> * Why do we want to "can resolve module arguments as well." ? Might be obvious in-context, I'm just not creative as out of context as I currently am.

Some modules inject additional arguments into `args` or `specialArgs` for other parts of the module tree to use. Modules can use these arguments as part of their argument list and `evalModules` injects them “automagically”.

However, at the same time, everything not specified as a function argument by the module gets stripped from the arguments passed by `evalModules`. Since `load` (and therefore `findLoad`) specify their own argument list, anything apart from `config`, `options`, and `lib`, which are always passed, was stripped from the arguments and not forwarded to `haumea.lib.load`.

As a stopgap, #32 enabled using at least `pkgs` by making it an argument of the module function.

This PR builds on #32 to handle the general case of specifying `args`/`specialArgs` somewhere in the configuration and using it in another module. For this purpose, we capture `config` and use it to inject additional arguments from `config` in the custom `haumea` loader.

> * Is the refactoring of defaultWith a guaranteed to be non-function-altering refactoring or does it alter function? If it does, please also introduce me from the end backwards to the functional change in detail.

It does alter function in that it newly enables the pattern of passing arguments through `config._module.args`, which wasn't possible before. It is backwards-compatible, however, so any existing configuration should keep working.

> What stability aspects / breakage risks have you considered?

I considered that the patch may break existing users of `load`/`findLoad`. To avoid this, I verified both my own configuration and https://github.com/Lord-Valen/configuration.nix using `nix flake check` with the new loader (first commit).

The second commit in this PR is something we discussed in Matrix: instead of writing the argument injection logic ourselves, we could reuse `lib.applyModuleArgsIfFunction` from `nixpkgs`. However, that runs into the issue mentioned in the comment above, where `config`, `options`, and `lib` are always passed to the module function. This would cause backwards-incompatibility for existing modules. 

We could either drop the second commit and only merge the first, accept the breakage, or we rethink the approach in general.

2025-02-14 17:13 UTC, korrat commented
I've also just now re-tested to verify that my flake still builds with the first commit. The second runs into the backwards-incompatibility.

2025-02-14 23:52 UTC, blaggacao commented
Perfect, thanks a lot! I have low appetite for instability and/or hurried mitigation, and if I understood correctly the second commit would be breaking, so please carve that out into another PR and we can discuss there.

The first commit seems to have an access of an unbound variaböe `file` if I spotted that correctly, otherwise I have the context and it looks like a solid change that could be merged soon.

Please adapt the PR (first commit only), ping me again, and I'll have a final review.

2025-02-15 07:10 UTC, korrat commented
> Perfect, thanks a lot! I have low appetite for instability and/or hurried mitigation if something goes wrong, and if I understood correctly the second commit would be breaking, so please carve that out into another PR and we can discuss there.

Done. Once this PR is merged, I will rebase the commit and open the second PR for discussion.

> The first commit seems to have an access of an unbound variable `file` if I spotted that correctly, otherwise I have the context and it looks like a solid change that could be merged soon.

`file` is bound in the `let`, I think (second line after the arguments). But we may be talking about different variables.

> Please adapt the PR (first commit only), ping me again, and I'll have a final review.

Thank you! And *ping* :D

2025-02-16 22:00 UTC, blaggacao requested changes
Check this, may be an oversight.

2025-02-16 22:00 UTC, blaggacao commented on flake.nix
> +            context = name: ''while evaluating the argument `${name}' in "${file}":'';
Am I correctly seeing `file` to be unbound?

2025-02-16 22:03 UTC, merged

2025-02-16 22:03 UTC, blaggacao commented
Alright, thanks a lot!